version: '3'

services:
  frontend:
    build: ./app/frontend
    ports:
      - 80:80
    command: [nginx-debug, '-g', 'daemon off;']
  backend:
    build: ./app/backend
    ports:
      - 8080:8080
